- README.md
Using mdx-deck/themes works without any extra installs, while ok-cli does not.
> Update README.md to fix the theme import

- lib/loader.js
Currently it's not possible to use tables because they're
parsed as slides. This ensures that a slide delimiter starts
at the beginning of the line.
> Improve slide parsing

- src/Appear.js
- src/Presenter.js
- src/Slide.js
- src/index.js
- test/index.js
Check if slide active status has changed and reset the steps if the status has changed. Extend `withSlide` to also provide the slide active status.
> Fix Appear handling

- docs/theming.md
Just as in PR #105, I have updated the docs to correctly import the base theme as a default import.
> Corrects named export to default export in theming documentation

- README.md
When I was attempting to create a custom theme and following the example, I noticed that only the new styles I was seeing were the ones I had added. No extension of the base theme was taking place. I logged out the `theme` object I was importing and found it was `undefined`. This is because `theme` is not a named export (at least not under that name). The `base` theme is exported under the `default` name in the distributed code. Thus, I corrected the documentation here to reflect the theme as a default export. This should also be done for the theme documentation, which I will do as a follow up to this PR.
> Correct named import of theme to default import for custom themes

- lib/dev.js
I was having issues starting the server and then saw the extra comma.
```
> npm run start
> intern-project-pres@1.0.0 start /Users/benjaminmodayil/Documents/sites/intern-project-pres
> mdx-deck deck.mdx
[mdx-deck] starting dev server
/Users/benjaminmodayil/Documents/sites/intern-project-pres/node_modules/mdx-deck/lib/dev.js:26
)
^
SyntaxError: Unexpected token )
at createScript (vm.js:53:10)
at Object.runInThisContext (vm.js:95:10)
at Module._compile (module.js:543:28)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/Users/benjaminmodayil/Documents/sites/intern-project-pres/node …
```
> Removed comma from dev.js

- src/Presenter.js
Related to #122.
Slide number in presenter mode is using `index` so it shows `0` to `n-1` but should be `1` to `n`.
> Fix slide index in presenter view

- README.md
- cli.js
- docs/advanced.md
- lib/config.js
- package-lock.json
- package.json
Based on #112. 
1. Add a `--webpack` option to the CLI to point to a custom config
2. Automatically look for a `webpack.config.js` from the CLI using `find-up` as [done here in x0](https://github.com/c8r/x0/blob/master/cli.js#L114-L119).
3. Use `webpack-merge` to merge with the built-in config
> Add support for custom webpack config

- templates/basic/.gitignore
When running `npm init deck path-to-deck`, the initial commit contains the entire `node_modules/` directory. This PR adds a `.gitignore` file to ignore that and the generated build files (`dist/`).
> Add .gitignore to basic template

- src/SlideDeck.js
- src/constants.js
Particularly useful when using an external clicker such as the Logitech
r400 which sends PgUp/PgDown keys for the left/right arrows.
> Support Page up/down keys

- docs/theming.md
Resolves #195 by clarifying that all colors keys are required for theming to work properly.
> Clarify that all colors keys are required for theming to work properly

- src/Root.js
Thanks for a great library! This PR fixes a small typo I noticed in `Root`s `PropTypes` while reading the `mdx-deck` source. The pre-commit hook seems to have altered some formatting, but the essential change happens on L27 of the diff (just removing a stray "s").
> Fix typo in Root PropTypes.

- package-lock.json
- package.json
Hello : )
I found that copy/pasting markdown links to [CodeSandbox](https://codesandbox.io/) (and, in general, using images wrapped in links) wasn't working as expected, so [I fixed it](https://github.com/johno/remark-unwrap-images/pull/2).
I hope this is OK to merge.
Thank you very much!
> Upgrade remark-unwrap-images

- src/Appear.js
Hi,
`Appear` children can be a single element so PropTypes should not required an array
> Fix Appear children PropTypes

- src/Appear.js
Currenly,`<Appear/>` set its children style props to `{ visibility: ... }`
With this PR, if a child had a pre-existing style, it will be kept
> [Appear] keep style of children if exists

- src/layouts/FullScreenCode.js
In cases where code sample is too large for the slide, presenters can now scroll to show more.
> Allow overflow for FullScreenCode

- src/SlideDeck.js
I ran into an issue when I was running a hosted version of an mdx-deck, and I think this is the cause. There were localStorage keys changing outside of these two, and I think the ", 10" in this condition was causing it to always be true.
I ran the tests and they still pass, and the demo still looked to be working. @jxnblk Were you attached to this ", 10"? Or was it just a stray bit of code?
The resulting behavior was a total crash of mdx-deck since it managed to set the step to NaN. I tried to reproduce locally by adding and changing a custom localStorage key, but it seems like the development version of react gives this warning and doesn't actually set the prop:
```
react-dom.development.js:515 Warning: Received NaN for the `step` attribute. If this is expected, cast the value to a …
```
> Take out ", 10" from an if check

- README.md
Thanks for mdx-deck, it is really awesome!
I made this library to do live React and JS coding in the slides. I would be honoured to be mentioned in the Readme.
I would also really appreciate some feedback from anyone who has time someday.
repo: https://github.com/JReinhold/mdx-deck-live-code
demo: https://reinhold.is/live-coding-in-slides
> Add mdx-deck-live-code as external library

- src/themes/base.js
- test/__snapshots__/index.js.snap
Fixes the issues with nested lists where the font size would grow exponentially with each nested list. This is fixed by adding a couple of css rules into the base theme to make sure the font size of the nested lists is inherited.
Thanks @tamagokun for the example!
Nested lists before:
Nested lists after:
Fixes #198.
> Target nested lists to ensure font size is the same

- lib/config.js
This adds support for importing components with a .jsx file extension. Webpack will also resolve these if no extension is provided.
For example:
import FancyComponent from './components/Fancy'
(will resolve to either Fancy.js and Fancy.jsx)
Solves #231
Cleaned up version of #237
> Support .jsx components

- src/Code.js
I apologize for the big change here, it seems that prettier has not been run on these files, but is now being applied in a precommit hook?
Anyway:
This fixes a tiny little bug where the default language in the `<Code />` component uses the string `javascripts` instead of `javascript`. It also fixes a typo: `getLangauge` => `getLanguage`.
> Fix default language for syntax highlighting

- lib/build.js
For example, I was hit by this bug: https://github.com/webpack-contrib/terser-webpack-plugin/issues/66 And mdx-deck was silently failing (and worse; making it look like it was successful).
This patch will guard against these kinds of issues in the future.
The complete error I managed to expose was:
```
Error: main.js from Terser
TypeError: Cannot read property 'minify' of undefined
at minify (<path>/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
at module.exports (<path>/node_modules/terser-webpack-plugin/dist/worker.js:13:40)
at handle (<path>/node_modules/worker-farm/lib/child/index.js:44:8)
at process.<anonymous> (<path>/node_modules/worker-farm/lib/child/index.js:51:3)
at process.emit (events.js:182:13)
at emit (internal/child_process.js:811:12)
at process._tickCallback …
```
> Surface compilation errors from webpack

- src/Appear.js
Howdy! First-time contributor here.
Currently, `Appear` resets to the first step when you change slides, causing its content to disappear during the transition to the next slide. You can see this [in the demo deck](https://jxnblk.com/mdx-deck/#9.4):
This is caused by `Appear` receiving a new `deck` object with `step={0}` when the transition occurs. The fix in this PR is to have `Appear` ignore new `step` values when the `deck` it receives has `active={false}`.
Please let me know if there's anything else you need from me here.
> Prevent Appear from resetting when changing slides

- packages/mdx-deck/lib/config.js
This change adds the ability to redefine configurations of webpack loaders that are set by internal config.
For example, to use additional remark plugins they should be passed to mdx-loader. Currently, it is not possible to manually configure mdx-loader since it always set by internal webpack config and if we add it into own config then two instances of mdx-loader will be configured.
> Take loaders in account when merging webpack configs

- docs/api.md
- packages/components/src/AspectRatioSlide.js
- packages/components/src/index.js
- packages/components/src/useTheme.js
Exports the `useTheme` hook so user components can access the theme without adding emotion as a peer dependency.
> Add useTheme hook

- packages/mdx-deck/README.md
👋 This PR adds a talk I recently gave to the examples section of the README. This talk uses mdx-deck 2.x, which there aren't as many examples of in that section compared to 1.x.
Here's the talk [source code](https://github.com/developermode/mdx-talk). I'm using a custom provider to add a footer to the presentation, as well as other theme customizations and speaker notes.
> Add mdx-talk presentation to Real Examples

- packages/loader/index.js
The dev server would silently hang when a syntax error was encountered in the @mdx-deck/loader module. You would only see the error after pressing ctrl+c to exit the process manually.
Before: https://streamable.com/7dpju
After: https://streamable.com/0jdz8
> fix(loader): syntax errors in dev mode

- packages/gatsby-theme/gatsby-node.js
When adding a custom basePath on a site with only one deck slide transitions move to the index path. `basePath` should be passed to context.
Here's a [repro](https://github.com/bkegley/gatsby-theme-mdx-deck-base-path)
> fix basePath issue on single deck site

- packages/gatsby-theme/src/components/deck.js
Slides were unmounting on every render because the `Mode` component was always changing
> Fix unmount on every render

- packages/gatsby-theme/gatsby-node.js
When building on a windows machine, slugs maintain a windows path
format (i.e., slides were located at http://localhost:8000/\hello)
Forced npm path module to use posix formats to fix this.
> Fix slug generation in windows

- packages/gatsby-theme/gatsby-config.js
- packages/gatsby-theme/package.json
- yarn.lock
Added [gatsby-remark-import-code](https://github.com/pomber/gatsby-remark-import-code) to the gatsby-plugin-mdx config.
This is particularly useful for people using Code Surfer, but it can also be used with any "vanilla" code block.  
It transforms code blocks from:
````md
```js file=./hello-world.js
```
````
into:
````md
```js
function helloWorld() {
return "hello world";
}
```
````
> Add plugin to import code blocks from files

- packages/gatsby-theme/gatsby-node.js
When the `basePath` is exactly `"/"` then the resulting path for printing is `//print`. See #440 
This PR makes sure there is no double slash reusing logic needed for matching unknown paths.
> Use correct path for print (fixes #440)

- packages/mdx-deck/README.md
In the example layout code, the CSS height was erroneously set to 100vw instead of 100vh.
> Change height: 100vw to 100vh in readme

- docs/demo.mdx
- docs/package.json
- docs/themes.md
- examples/aspect-ratio/deck.mdx
- examples/head/deck.mdx
- examples/images/deck.mdx
- examples/layouts/deck.mdx
- examples/prism/deck.mdx
- examples/provider/deck.mdx
- examples/syntax-highlighting/deck.mdx
- examples/themes/theme.js
This fixes the docs pages and examples that still used the incorrect v2 package names (`@mdx-deck/themes`, `@mdx-deck/components`).
> Update docs & examples to use v3 package imports

- packages/gatsby-theme/src/components/app.js
I came across this issue when I was developing a theme, and I was checking if the user was in "normal" mode, I saw that it starts with "normal", but if you hit `escape`, it becomes "NORMAL", capitalised.
I checked the code and found out that the constants are not used on the `app.js`,  so I fixed it.
> Using constant for normal mode on step 0

- packages/website-pdf/cli.js
While trying to export an mdx deck presentation using the `website-pdf` package, I got the following error:
```sh
yarn run v1.21.1
$ ./cli.js http://localhost:8000/print -o ../../docs/dist
/Users/gregoiremielle/Documents/dev/mdx-deck/packages/website-pdf/node_modules/minimist-options/index.js:74
throw new TypeError(`Expected "${key}" default value to be ${type}, got ${typeof props.default}`);
^
TypeError: Expected "width" default value to be string, got number
at Object.keys.forEach.key (/Users/gregoiremielle/Documents/dev/mdx-deck/packages/website-pdf/node_modules/minimist-options/index.js:74:12)
at Array.forEach (<anonymous>)
at buildOptions (/Users/gregoiremielle/Documents/dev/mdx-deck/packages/website-pdf/node_modules/minimist-options/index.js:36:23)
at meow …
```
> Fix website-pdf CLI flags defaults

- packages/mdx-deck/README.md
Adds an example deck to the readme that illustrates use of some custom components.
> Add "intro to webdev" example deck.

- packages/mdx-deck/README.md
The last pull request introduce a wrong markdown syntax leading to a weird output of link-text and link instead of a text that is a link.
This Pull Request fixes that.
Sorry for the inconvinience.
> Fix markdown syntax for example deck.
