jxnblk/mdx-deck

docs/Layout.js, docs/index.mdx, src/index.js
=> Add hash change listeners

lib/loader.js, package.json
=> Use normalize-newline for cross-platform support

README.md, docs/index.mdx, package.json, src/Flex.js, src/Mono.js, src/Notes.js, src/Presenter.js, src/Slide.js, src/components.js, src/context.js, src/index.js, test/__snapshots__/components.js.snap
=> Speaker notes

src/entry.js, src/index.js
This allows the presentation state to be passed in as props to custom provider components
=> Move custom Provider into main app

src/components.js, test/__snapshots__/components.js.snap
=> Remove default target blank from links

src/Carousel.js, src/Dots.js, src/Flex.js, src/Image.js, src/Presenter.js, src/Root.js, src/Slide.js, src/Timer.js, src/Zoom.js, src/components.js, src/index.js
Add PropType definitions for documentation purposes.
=> Add PropType definitions

docs/index.mdx, src/FragmentBlock.js, src/index.js
This is only a proof of concept. It would enable to skip through fragments. 
Currently it would listen to key up and key down (to not clash with key left/right inside the main component).
=> Add Fragments Component

README.md, docs/presenter.mdx, src/index.js, test/index.js
- Ignore key events when activeElement is not the body
- Require `Option` key for toggling modes
- Placeholder for overview mode toggle
=> Update keyboard shortcuts

README.md
=> Update syntax highlighting documentation

docs/Counter.js, docs/index.mdx
=> Add React component example

src/Dots.js, src/Provider.js, src/index.js, test/index.js
- Adds default Provider component
- Moves dots to default Provider
- Adds invisible buttons to the left and right sides of the viewport for basic mobile navigation
Related to #6
=> Basic mobile support

src/Notes.js, src/Overview.js, src/Presenter.js, src/Slide.js
=> Only add notes when rendered in the main view

src/index.js
=> Prevent last slide from cycling to beginning

src/index.js
=> Disable mouse swipe

package.json
Adds a field to package.json so a link appears to the source on NPM
=> Add link to repository

lib/html.js, lib/pdf.js, lib/screenshot.js, package.json
=> Use mkdirp

lib/html.js, package-lock.json, package.json
=> Fix node build

docs/code.js, docs/index.mdx, lib/config.js, package-lock.json, package.json, src/SlideDeck.js
=> Fix for localStorage race condition

lib/config.js, src/SlideDeck.js
- Also adds overflow hidden to the body to prevent scrolling on iOS
=> Fix swipe direction

cli.js, lib/config.js, lib/dev.js, lib/overlay.js
I normally do all my JS coding from my home server.  This PR enables to
to run the dev + hot client server correctly.
=> Specify host cli option

docs/index.mdx, lib/config.js
=> Remove overflow hidden from body

README.md
Adds link to egghead video about creating a custom Provider component for your decks
=> Adds Egghead video on Custom Providers to README.md

README.md
https://github.com/pranaygp/mdx-code
=> Add mdx-code as a third party library

README.md
I found it useful when deploying it. There might be some other options, too, I have not found.
=> Adds -h to CLI options

package-lock.json, package.json
=> Hot fix for babel-plugin-styled-components

src/Button.js, src/Presenter.js, src/Timer.js
closes #81
Example: https://site-fimspttruq.now.sh/
=> Adds Button to go to normal view in presenter mode

docs/advanced.md
Hey,
While I was Learning,I found out that  MDX's,*MDX-Provider*  Documentation's link was not redirected correctly. I think this'll solve the error. 
Keep up the good Work :+1:
=> updated MDX Provider's Docs Link

cli.js
Add documentation for the previously undocumented `--version` flag.
=> Document "--version" flag

packages/components/src/Grid.js, packages/components/src/MDXDeck.js, packages/components/src/Zoom.js
=> Add grid view

docs/theming.md
Apparently the Slide root component is Slide, not Slides
=> Fix reference in theming.md

packages/mdx-plugin/__snapshots__/test.js.snap, packages/mdx-plugin/index.js
=> Rename internal layout const

docs/demo.mdx
Just fixed typo in first slide :-)
=> Fix typo on home page

packages/components/src/GoogleFonts.js, packages/components/src/Head.js, packages/components/src/Provider.js, packages/mdx-deck/lib/entry.js
Refactor the Head component to work in all slides and not remove elements during rehydration
=> Fix for Google fonts & Head

docs/theming.md, packages/components/src/MDXDeck.js, packages/components/src/Provider.js, packages/components/src/index.js
=> feat: themable Presenter

docs/advanced.md
Provide an example of how to define your own custom Provider and clarify how to set a Provider in your custom theme. Hopefully this will save folks a bit of time when they are looking into creating their own custom Provider.
=> Update Advanced Docs

packages/export/index.js
Quick fix to support webpack config in export (code backported).
=> Add support for webpack config

packages/gatsby-theme/gatsby-config.js, packages/gatsby-theme/package.json
=> Add compile es6 plugin to gatsby theme

packages/gatsby-theme/gatsby-node.js
=> Adjust slug in single deck mode

packages/gatsby-theme/src/hooks/use-keyboard.js
Change slides on up/down arrow press. 
Just bought [this clicker](https://www.amazon.de/gp/product/B07BJZPGLZ/) and it sends up/down arrow keys.
=> Support more clickers

packages/gatsby-theme/gatsby-node.js
=> Adjust content digest

packages/themes/notes.js
Notes themes is break with v4.
=> fix color on notes themes

packages/mdx-deck/package.json
Fix for #654
Add missing gatsby-source-filesystem dep.
=> Add missing dep.
